version: '3.5'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-withdrawal
    command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
    ports:
      - '25432:5432'
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=elastum

  waitpostgres:
    image: postgres:13-alpine
    links:
      - postgres
    depends_on:
      - postgres
    entrypoint:
      - bash
      - -c
      - 'until /usr/local/bin/psql "host=postgres port=5432 dbname=elastum user=testuser password=testpass" -c "SELECT 1"; do sleep 5; done'

  redis:
    image: redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
#      - taip galima pakrauti duomenis paleidziant sistema
#      - ./rabbitmq/etc/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
#      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq.json
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
