version: '3.5'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
#      - taip galima pakrauti duomenis paleidziant sistema
#      - ./rabbitmq/etc/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
#      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq.json
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
